### ISSUE TITLE
create coding checklist & guideline

### ISSUE THREAD

**Issue by dotrungkien** [dotrungkien/eth-code-base#5]
## Coding guideline
- Tạo nhánh mới với mỗi task, sau khi hoàn thành thì tạo pull sang master

## Pull request checklist
mỗi khi pull request thì mình sẽ ghi theo mẫu như sau trong pull

---

### Description
 (description here)

### Type of change
  (Implement/Fixbug/Release)
### Checklist:
- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ]  I have commented my code, particularly in hard-to-understand areas.
- [ ]  I have made corresponding changes to the documentation.
- [ ]  My changes generate no warnings.
- [ ]  I ran `yarn test` in the root folder with success and extended the tests to cover all changes.
- [ ]  I have tested my code with an ethereum test network.
